package by.tr.hotelbooking.controller.command;

public enum CommandName {
    AFTER_SIGN_IN, AFTER_SIGN_UP, SHOW_USERS,
    SIGN_IN, SIGN_UP, REDIRECT,
    SHOW_MAIN_PAGE, CHANGE_LOCALE, EXIT,
    SHOW_HOTELROOMS, SHOW_PAGE_FOR_ADD_HOTELROOM,
    SHOW_EDIT_HOTELROOM_PAGE, ADD_HOTELROOM,
    AFTER_HOTELROOM_OPERATION, REMOVE_HOTELROOM,
    MAKE_ORDER, EDIT_HOTELROOM, SHOW_MAKE_ORDER_PAGE
}
