package by.tr.hotelbooking.controller.command;

public enum CommandName {
    SHOW_USERS, SIGN_IN, SIGN_UP, REDIRECT,
    CHANGE_LOCALE, EXIT, SHOW_HOTELROOMS, SHOW_PAGE_FOR_ADD_HOTELROOM,
    SHOW_EDIT_HOTELROOM_PAGE, ADD_HOTELROOM, REMOVE_HOTELROOM, MAKE_ORDER,
    EDIT_HOTELROOM, SHOW_PAGE_FOR_MAKE_ORDER, SHOW_ORDERS, SHOW_COMMENTS,
    ADD_COMMENT, DELETE_COMMENT, FIND_HOTELROOMS, ADD_CONTRACT,
    ACCEPT_CONTRACT, DECLINE_CONTRACT, SHOW_CONTRACTS,
    SHOW_USER_CONTRACTS, SHOW_NEW_OFFERS, CANCEL_ORDER
}
